name: Deploy to ECS Test
on:
  workflow_dispatch:
    inputs:
      run_migration:
        type: string  # Changed to string
        default: "true"  # Treat as string

jobs:
  deploy_to_test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World from Deploy to ECS Test
        run: echo "Hello from Deploy to ECS Test"
      
      - name: Set output for run_migration
        id: set_output
        run: echo "::set-output name=run_migration::${{ github.event.inputs.run_migration }}"

    outputs:
      run_migration: ${{ steps.set_output.outputs.run_migration }}
