name: Hello World Deploy
on:
  workflow_run:
    workflows: ["Create Tag"]
    branches:
      - main
    types:
      - completed
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  hello_world_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hello World Deploy
        run: echo 'Hello, World! Deploy to ECS Test'
