name: workflow_01
on:
  workflow_dispatch:
    inputs:
      trigger_workflow_02:
        description: 'Trigger workflow 02 (true or false)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if workflow_02 should be triggered
        if: ${{ inputs.trigger_workflow_02 == 'true' }}
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --data '{"event_type": "Trigger Workflow"}'
