name: Hello World Deploy
on:
  workflow_run:
    workflows: ["Create Tag"]
    branches:
      - main
    types:
      - completed
  push:
    branches:
      - main
  workflow_dispatch:
   inputs:
      run_migration:
        description: 'Run database migration after deployment (true/false)'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'

jobs:
  hello_world_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hello World Deploy
        run: echo 'Hello, World! Deploy to ECS Test'
      - name: Set run_migration output
        run: echo "run_migration=${{ github.event.inputs.run_migration || 'false' }}" >> $GITHUB_OUTPUT
        id: set_run_migration

    outputs:
      run_migration: ${{ steps.set_run_migration.outputs.run_migration }}
