name: ECS Test Deployment
on:
  workflow_run:
    workflows: ["Create Tag"]
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
    inputs:
      trigger_db_migration:
        description: "Should trigger Test DB Migration after completion"
        required: true
        type: boolean

jobs:
  deploy_to_test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello from ECS Test Deployment
        run: echo "Hello from ECS Test Deployment"

  set_output:
    runs-on: ubuntu-latest
    needs: deploy_to_test
    outputs:
      trigger_db_migration: ${{ steps.set_trigger.outputs.trigger_db_migration }}
    steps:
      - name: Set trigger for Test DB Migration
        id: set_trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "::set-output name=trigger_db_migration::${{ toJSON(github.event.inputs.trigger_db_migration) }}"
