name: Test Database Migration
on:
  workflow_run:
    workflows: ['Deploy to ECS Test']
    types:
      - completed

jobs:
  run_database_migration:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.run_migration == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello World from Test Database Migration
        run: echo "Hello from Test Database Migration"
