name: workflow_02
on:
  repository_dispatch:
    types: [Trigger Workflow]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow 02 triggered by repository dispatch."
      - name: Checkout code
        uses: actions/checkout@v3
