name: Hello World Database Migration
on:
  workflow_run:
    workflows: ['Hello World Deploy']
    types:
      - completed
    branches:
      - main

jobs:
  hello_world_migration:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.event != 'workflow_dispatch' ||
       github.event.workflow_run.outputs.run_migration == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World Migration
        run: echo 'Hello, World! Database Migration'
