name: Test DB Migration
on:
  workflow_run:
    workflows: ["ECS Test Deployment"]
    branches:
      - main
    types:
      - completed

jobs:
  run_database_migration:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.inputs.trigger_db_migration == 'true' }}
    steps:
      - name: Hello from DB Migration
        run: echo "Hello from DB Migration"
