
name: Starter Workflow

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment Name'
        required: true

env:
  ROLE_NAME: ${{ vars.ROLE_NAME }}
  INSTANCE_TYPE: ${{ vars.INSTANCE_TYPE }}
  INSTANCE_PROFILE_NAME: ${{ vars.INSTANCE_PROFILE_NAME }}
  APP_NAME: ${{ vars.APP_NAME }}
  ENV_NAME: ${{ vars.ENV_NAME }}
  VPC_ID: ${{ vars.VPC_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  SECURITY_GROUP_NAME: ${{ vars.SECURITY_GROUP_NAME }}
  SOLUTION_STACK: ${{ vars.SOLUTION_STACK }}

jobs:
  call-eb-provisioning-template:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.env_name }}
    steps:
      - name: Call EB Provisioning Workflow
        uses: deecodz/Provisioning_template/.github/workflows/provision-eb.yml@main
        with:
          role_name: ${{ env.ROLE_NAME }}
          instance_type: ${{ env.INSTANCE_TYPE }}
          instance_profile_name: ${{ env.INSTANCE_PROFILE_NAME }}
          app_name: ${{ env.APP_NAME }}
          env_name: ${{ env.ENV_NAME }}
          vpc_id: ${{ env.VPC_ID }}
          aws_region: ${{ env.AWS_REGION }}
          security_group_name: ${{ env.SECURITY_GROUP_NAME }}
          solution_stack: ${{ env.SOLUTION_STACK }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
