on:
  workflow_dispatch:

jobs:
  provision-eb-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: sudo apt install awscli

      - name: Provision Elastic Beanstalk instance
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws elasticbeanstalk create-environment \
            --application-name my-app \
            --environment-name my-env \
            --region us-east-1 \
            --tier Type=Standard,Name=WebServer \
            --solution-stack-name "64bit Amazon Linux 2015.03 v2.0.0 running Python 3.4"
