name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment Name'
        required: true

jobs:
  call-workflow:
    uses: deecodz/Provisioning_template/.github/workflows/provision-eb.yml@main
    # secrets: inherit
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      env_name: ${{ github.event.inputs.env_name }}
