
name: Starter Workflow

on:
  workflow_dispatch:

jobs:
  call-eb-provisioning-template:
    uses: deecodz/Provisioning_template/.github/workflows/provision-eb.yml@main
    with:
      role_name: ${{ github.event.inputs.role_name }}
      instance_profile_name: ${{ github.event.inputs.instance_profile_name }}
      app_name: ${{ github.event.inputs.app_name }}
      env_name: ${{ github.event.inputs.env_name }}
      vpc_id: ${{ github.event.inputs.vpc_id }}
      aws_region: ${{ github.event.inputs.aws_region }}
      security_group_name: ${{ github.event.inputs.security_group_name }}
      solution_stack: ${{ github.event.inputs.solution_stack }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
