
name: Starter Workflow

on:
  workflow_dispatch:
    inputs:
      role_name:
        description: 'Role Name'
        required: true
      instance_profile_name:
        description: 'Instance Profile Name'
        required: true
      app_name:
        description: 'Elastic Beanstalk Application Name'
        required: true
      env_name:
        description: 'Elastic Beanstalk Environment Name'
        required: true
      vpc_id:
        description: 'VPC ID'
        required: true
      aws_region:
        description: 'AWS Region'
        required: true
      security_group_name:
        description: 'Name for the new Security Group'
        required: true
      solution_stack:
        description: 'Elastic Beanstalk Solution Stack'
        required: true


jobs:
  call-eb-provisioning-template:
    uses: deecodz/Provisioning_template/.github/workflows/provision-eb.yml@main
    with:
      role_name: ${{ github.event.inputs.role_name }}
      instance_profile_name: ${{ github.event.inputs.instance_profile_name }}
      app_name: ${{ github.event.inputs.app_name }}
      env_name: ${{ github.event.inputs.env_name }}
      vpc_id: ${{ github.event.inputs.vpc_id }}
      aws_region: ${{ github.event.inputs.aws_region }}
      security_group_name: ${{ github.event.inputs.security_group_name }}
      solution_stack: ${{ github.event.inputs.solution_stack }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
