on:
  workflow_dispatch:

jobs:
  provision-eb-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: sudo apt install awscli

      - name: Set up AWS credentials
        run: |
          echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.bashrc
          echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.bashrc
          source ~/.bashrc

      - name: Provision Elastic Beanstalk instance
        run: |
          aws elasticbeanstalk create-environment \
            --application-name my-app \
            --environment-name my-env \
            --region us-east-1 \
            --tier WebServer \
            --solution-stack-name "64bit Amazon Linux 2018.03 v2.9.3 running Python 3.6"
