on:
  workflow_dispatch:
    inputs:
      instance_profile_name:
        description: 'Instance Profile Name'
        required: true
        default: 'test-instance-profile'
      app_name:
        description: 'Elastic Beanstalk Application Name'
        required: true
        default: 'my-app'
      env_name:
        description: 'Elastic Beanstalk Environment Name'
        required: true
        default: 'my-env-newer'
      vpc_id:
        description: 'VPC ID'
        required: true
        default: 'vpc-08be2d942d24fc036'
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      security_group_name:
        description: 'Name for the new Security Group'
        required: true
        default: 'eb-sg'
      solution_stack:
        description: 'Elastic Beanstalk Solution Stack'
        required: true
        default: '64bit Amazon Linux 2023 v4.0.3 running Python 3.9'

jobs:
  provision-eb-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Set up AWS credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ${{ github.event.inputs.aws_region }}

      - name: Create instance profile and associate role
        run: |
          aws iam get-instance-profile --instance-profile-name ${{ github.event.inputs.instance_profile_name }} \
          || (aws iam create-instance-profile --instance-profile-name ${{ github.event.inputs.instance_profile_name }} &&
          aws iam add-role-to-instance-profile --role-name test-role --instance-profile-name ${{ github.event.inputs.instance_profile_name }})

      - name: Create Elastic Beanstalk Application
        run: | 
          aws elasticbeanstalk describe-applications --application-name ${{ github.event.inputs.app_name }} \
          || aws elasticbeanstalk create-application --application-name ${{ github.event.inputs.app_name }} --description "My application for Elastic Beanstalk"

      - name: Create New Security Group
        id: create_sg  # Assign an ID to the step
        run: |
          # Try to fetch existing security group ID
          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=${{ github.event.inputs.security_group_name }}" "Name=vpc-id,Values=${{ github.event.inputs.vpc_id }}" | jq -r '.SecurityGroups[0].GroupId')
          
          # If security group doesn't exist, create a new one
          [[ ! -z "$SECURITY_GROUP_ID" ]] || SECURITY_GROUP_ID=$(aws ec2 create-security-group --group-name ${{ github.event.inputs.security_group_name }} --description "Security group for Elastic Beanstalk" --vpc-id ${{ github.event.inputs.vpc_id }} | jq -r '.GroupId')
          
          # Add SSH (port 22) inbound rule; the "|| true" ensures that if the rule already exists, the command won't fail
          aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr 0.0.0.0/0 || true
      
          # Add HTTP (port 80) inbound rule
          aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 80 --cidr 0.0.0.0/0 || true
          
          # Set the output variable for this step
          echo "::set-output name=sg_id::$SECURITY_GROUP_ID"
          
          # Sleep for a short delay to allow for AWS resource propagation
          sleep 10


          
      - name: Provision Elastic Beanstalk instance
        run: |
          aws elasticbeanstalk create-environment \
            --application-name ${{ github.event.inputs.app_name }} \
            --environment-name ${{ github.event.inputs.env_name }} \
            --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=${{ github.event.inputs.instance_profile_name }} \
            Namespace=aws:autoscaling:launchconfiguration,OptionName=EC2KeyName,Value=testkey \
            Namespace=aws:autoscaling:launchconfiguration,OptionName=SecurityGroups,Value=${{ github.event.inputs.security_group_name }} \
            --region ${{ github.event.inputs.aws_region }} \
            --tier Type=Standard,Name=WebServer \
            --solution-stack-name "${{ github.event.inputs.solution_stack }}"
