name: Create Tag

on:
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch info and generate tag
        id: tag_info
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          
          DATE=$(date +'%Y.%m.%d')
          LATEST_TAG=$(git tag -l "${DATE}.*" | sort -V | tail -n 1)
          
          BUILD_NUMBER=$(printf "%03d" $((10#${LATEST_TAG##*.} + 1)))
          BUILD_NUMBER=${BUILD_NUMBER:-001}
          
          TAG="${DATE}.${BUILD_NUMBER}"
          [ "$BRANCH_NAME" != "$DEFAULT_BRANCH" ] && TAG="${TAG}.${BRANCH_NAME}"
          
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
          echo "release_version=${TAG}" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ env.RELEASE_VERSION }}
          git push origin ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
