name: Create Tag

on:
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and push tag
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          DATE=$(date +'%Y.%m.%d')
          
          get_next_build_number() {
            local prefix="$1"
            git tag -l "${prefix}*" | sort -V | tail -n 1 | awk -F. '{print $NF+1}'
          }
          
          BUILD_NUMBER=$(get_next_build_number "${DATE}.")
          BUILD_NUMBER=$(printf "%03d" $BUILD_NUMBER)
          
          TAG="${DATE}.${BUILD_NUMBER}"
          [[ "$BRANCH_NAME" != "$DEFAULT_BRANCH" ]] && TAG="${TAG}.${BRANCH_NAME}"
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $TAG
          git push origin $TAG
          
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
